### List all seasons
GET http://localhost:8080/seasons
Content-Type: application/json

### Create a season
POST http://localhost:8080/seasons
Content-Type: application/json

{
  "season": 6,
  "episodes": [
    {
      "episode_number": 1,
      "title": "Members Only",
      "director": "Tim Van Patten",
      "writer": "Terence Winter",
      "description": "Tony faces questions about his leadership, while Carmela takes steps to secure her financial future.",
      "imdb_rating": 9.1
    }
  ]
}

### List all episodes from a season
GET http://localhost:8080/seasons/6/episodes
Content-Type: application/json

### Create an episode in a season
POST http://localhost:8080/seasons/6/episodes
Content-Type: application/json

{
  "episode_number": 2,
  "title": "Join the Club",
  "director": "David Nutter",
  "writer": "David Chase",
  "description": "Tony has a series of unsettling dreams, while Carmela seeks comfort in her newfound independence.",
  "imdb_rating": 9.3
}

### Update episode
PUT http://localhost:8080/seasons/6/episodes/1
Content-Type: application/json

{
  "episode_number": 1,
  "title": "Members Only - Teste ",
  "director": "Tim Van Patten",
  "writer": "Terence Winter",
  "description": "Tony faces questions about his leadership, while Carmela takes steps to secure her financial future.",
  "imdb_rating": 9.1
}

### Delete episode
DELETE http://localhost:8080/seasons/6/episodes/2
Content-Type: application/json


### Delete a season
DELETE http://localhost:8080/seasons/6
Content-Type: application/json

### Try to update a season
PUT http://localhost:8080/seasons/1
Content-Type: application/json

{
  "season": 1,
  "episodes": [
    {
      "episode_number": 1,
      "title": "Members Only",
      "director": "Tim Van Patten",
      "writer": "Terence Winter",
      "description": "Tony faces questions about his leadership, while Carmela takes steps to secure her financial future.",
      "imdb_rating": 9.1
    }
  ]
}

### Get episode details
GET http://localhost:8080/seasons/1/episodes/1
Content-Type: application/json

### Get episode title
GET http://localhost:8080/seasons/1/episodes/1/title
Content-Type: text/plain

### Get episode rating
GET http://localhost:8080/seasons/1/episodes/1/rating
Content-Type: text/plain

### Get episode description
GET http://localhost:8080/seasons/1/episodes/1/description
Content-Type: text/plain

### Get episode director
GET http://localhost:8080/seasons/1/episodes/1/director
Content-Type: text/plain

### Get episode writer
GET http://localhost:8080/seasons/1/episodes/1/writer
Content-Type: text/plain

